### ISSUE TITLE
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:383

### ISSUE THREAD

**Issue by huangshaoguang** [zju3dv/mvpose#17]
Hello!Thank you for your sharing.I  run "python ./src/m_utils/demo.py -d Shelf" and I get wrong.I test my torch and I think it's OK. Because torch.cuda.is_available() is True. What may be the reason?
python ./src/m_utils/demo.py -d Shelf
2019-06-27 16:29:10.994614: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-06-27 16:29:11.203000: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55c94cf37d70 executing computations on platform CUDA. Devices:
2019-06-27 16:29:11.203060: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
2019-06-27 16:29:11.226375: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3800000000 Hz
2019-06-27 16:29:11.227799: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55c94cee4a60 executing computations on platform Host. Devices:
2019-06-27 16:29:11.227844: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-06-27 16:29:11.228311: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.635
pciBusID: 0000:17:00.0
totalMemory: 10.73GiB freeMemory: 10.12GiB
2019-06-27 16:29:11.228351: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-06-27 16:29:11.233530: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-27 16:29:11.233567: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-06-27 16:29:11.233590: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-06-27 16:29:11.233997: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9845 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:17:00.0, compute capability: 7.5)
WARNING:tensorflow:From /home/admin888/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /home/admin888/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py:1624: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From /home/admin888/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2019-06-27 16:29:15.420931: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-06-27 16:29:15.421001: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-27 16:29:15.421019: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-06-27 16:29:15.421034: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-06-27 16:29:15.421366: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9845 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:17:00.0, compute capability: 7.5)
06-27 16:29:15 Generating testing graph on 1 GPUs ...
06-27 16:29:18 Initialized model weights from /home/admin888/Desktop/BodyPose/mvpose/backend/tf_cpn/log/model_dump/snapshot_350.ckpt ...
06-27 16:29:20 Current epoch is 350.
/home/admin888/Desktop/BodyPose/mvpose/backend/CamStyle/reid/models/resnet.py:49: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  init.kaiming_normal(self.feat.weight, mode='fan_out')
/home/admin888/Desktop/BodyPose/mvpose/backend/CamStyle/reid/models/resnet.py:50: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(self.feat.bias, 0)
/home/admin888/Desktop/BodyPose/mvpose/backend/CamStyle/reid/models/resnet.py:51: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(self.feat_bn.weight, 1)
/home/admin888/Desktop/BodyPose/mvpose/backend/CamStyle/reid/models/resnet.py:52: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(self.feat_bn.bias, 0)
/home/admin888/Desktop/BodyPose/mvpose/backend/CamStyle/reid/models/resnet.py:60: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.classifier.weight, std=0.001)
/home/admin888/Desktop/BodyPose/mvpose/backend/CamStyle/reid/models/resnet.py:61: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(self.classifier.bias, 0)
=> Loaded checkpoint '/home/admin888/Desktop/BodyPose/mvpose/backend/CamStyle/logs/market-ide-camstyle-re/checkpoint.pth.tar'
=> Start epoch 50 
/home/admin888/Desktop/BodyPose/mvpose/datasets/Shelf
  0%|                                                   | 0/239 [00:00<?, ?it/s]2019-06-27 16:29:24.543484: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument

Traceback (most recent call last):
  File "./src/m_utils/demo.py", line 95, in <module>
    pose_in_range = export ( test_model, test_loader, is_info_dicts=bool ( args.dumped_dir ), show=True )
  File "./src/m_utils/demo.py", line 44, in export
    show=show, plt_id=img_id )
  File "/home/admin888/Desktop/BodyPose/mvpose/src/models/estimate3d.py", line 43, in predict
    return self._estimate3d ( 0, show=show, plt_id=plt_id )
  File "/home/admin888/Desktop/BodyPose/mvpose/src/models/estimate3d.py", line 69, in _estimate3d
    affinity_mat = self.extractor.get_affinity ( data_batch, rerank=self.cfg.rerank )
  File "/home/admin888/Desktop/BodyPose/mvpose/backend/CamStyle/feature_extract.py", line 208, in get_affinity
    query_features = extract_features ( self.model, query_batch, 1, output_feature, use_gpu=use_gpu )
  File "/home/admin888/Desktop/BodyPose/mvpose/backend/CamStyle/feature_extract.py", line 37, in extract_features
    outputs = extract_cnn_feature ( model, imgs, output_feature, use_gpu=use_gpu )
  File "/home/admin888/Desktop/BodyPose/mvpose/backend/CamStyle/feature_extract.py", line 26, in extract_cnn_feature
    outputs = model ( inputs.squeeze (), output_feature )
  File "/home/admin888/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/admin888/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/admin888/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/admin888/Desktop/BodyPose/mvpose/backend/CamStyle/reid/models/resnet.py", line 70, in forward
    x = module(x)
  File "/home/admin888/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/admin888/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 338, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:383

**Comment by JiangWenPL** [comment]
Sorry I haven't meet with the issue before. But I believe some issues from other repos might be helpful https://github.com/fastai/fastai/issues/1566 Besides, you could try to run this program with only one visible GPU.

**Comment by dulibubai** [comment]
can you have the demo of read image from camera in real time and show the 3d result?

**Comment by dulibubai** [comment]
Now,I want to run the demo with camera capture in real time?

**Comment by huangshaoguang** [comment]
> Now,I want to run the demo with camera capture in real time?

It's not realtime  it's very slow. It's only about 0.5fps on RTX2080TI.So I gave up.

**Comment by dulibubai** [comment]
So do you have the demo code with images read from camera capture not from the datasat file path? I want to have a try?

**Comment by DongJT1996** [comment]
The 2D pose estimator CPN we used is a little slow but with higher accuracy. For faster speed, you may use the [openpose](https://github.com/CMU-Perceptual-Computing-Lab/openpose) as the 2D pose estimator.

**Comment by lan786** [comment]
@huangshaoguang  Hi, I've 6GB GPU (GTX1060). All the steps and compilations was done. When I try to run the Demo, it shows CUDA out of memory. When I changed the batch size from 32 to 4 in backend/tf_cpn/Detector2D.py (line 90) then it shows following error in Detector2D.py line 220.
heatmaps = heatmaps[i], crops=crops[i]
Kindly help me in this regard that how I can solve this problem?
Thanks
