### ISSUE TITLE
Campus_2019_11_30_08_40.pkl'

### ISSUE THREAD

**Issue by biexiangduo** [zju3dv/mvpose#35]
(base) pf@pf-System-Product-Name:~/mvpose$ python ./src/m_utils/demo.py -d Campus
/home/pf/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py:16: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.
    
  from jupyter_client.session import utcnow as now
2019-11-30 08:23:56.775808: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-11-30 08:23:56.851137: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-11-30 08:23:56.851452: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.607
pciBusID: 0000:01:00.0
totalMemory: 10.91GiB freeMemory: 10.52GiB
2019-11-30 08:23:56.851467: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0
2019-11-30 08:23:59.618169: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-30 08:23:59.618198: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 
2019-11-30 08:23:59.618204: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N 
2019-11-30 08:23:59.618289: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9755 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
2019-11-30 08:24:02.743015: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0
2019-11-30 08:24:02.743048: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-30 08:24:02.743054: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 
2019-11-30 08:24:02.743059: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N 
2019-11-30 08:24:02.743115: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9755 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
11-30 08:24:02 Generating testing graph on 1 GPUs ...
11-30 08:24:05 Initialized model weights from /home/pf/mvpose/backend/tf_cpn/log/model_dump/snapshot_350.ckpt ...
11-30 08:24:06 Current epoch is 350.
/home/pf/mvpose/backend/CamStyle/reid/models/resnet.py:49: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  init.kaiming_normal(self.feat.weight, mode='fan_out')
/home/pf/mvpose/backend/CamStyle/reid/models/resnet.py:50: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(self.feat.bias, 0)
/home/pf/mvpose/backend/CamStyle/reid/models/resnet.py:51: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(self.feat_bn.weight, 1)
/home/pf/mvpose/backend/CamStyle/reid/models/resnet.py:52: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(self.feat_bn.bias, 0)
/home/pf/mvpose/backend/CamStyle/reid/models/resnet.py:60: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(self.classifier.weight, std=0.001)
/home/pf/mvpose/backend/CamStyle/reid/models/resnet.py:61: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(self.classifier.bias, 0)
=> Loaded checkpoint '/home/pf/mvpose/backend/CamStyle/logs/market-ide-camstyle-re/checkpoint.pth.tar'
=> Start epoch 50 
 48%|██████████████████████████████████████████▎                                             | 38/79 [10:01<10:48, 15.83s/it]/home/pf/mvpose/src/m_utils/visualize.py:379: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  plt.subplot ( rows, cols, cam_id * cols + i + 2 )
/home/pf/mvpose/src/m_utils/visualize.py:379: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  plt.subplot ( rows, cols, cam_id * cols + i + 2 )
100%|████████████████████████████████████████████████████████████████████████████████████████| 79/79 [16:02<00:00, 12.19s/it]
Traceback (most recent call last):
  File "./src/m_utils/demo.py", line 95, in <module>
    time.localtime ( time.time () ) ) + '.pkl' ), 'wb' ) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/pf/mvpose/result/Campus_2019_11_30_08_40.pkl'

it seems there omiss a pkl file ? when the demo start, i have to shutdown the current picture,then would  continue.is it normal?

**Comment by JiangWenPL** [comment]
Probably you need to create the folder mvpose/result/ if you have downloaded the pickle files provided by us. 



    


            On 11/30/2019 08:46, biexiangduo wrote: (base) pf@pf-System-Product-Name:~/mvpose$ python ./src/m_utils/demo.py -d Campus

/home/pf/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py:16: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.

Install tornado itself to use zmq with the tornado IOLoop.

from jupyter_client.session import utcnow as now

2019-11-30 08:23:56.775808: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA

2019-11-30 08:23:56.851137: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero

2019-11-30 08:23:56.851452: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties:

name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.607

pciBusID: 0000:01:00.0

totalMemory: 10.91GiB freeMemory: 10.52GiB

2019-11-30 08:23:56.851467: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0

2019-11-30 08:23:59.618169: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:

2019-11-30 08:23:59.618198: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0

2019-11-30 08:23:59.618204: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N

2019-11-30 08:23:59.618289: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9755 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)

2019-11-30 08:24:02.743015: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0

2019-11-30 08:24:02.743048: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:

2019-11-30 08:24:02.743054: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0

2019-11-30 08:24:02.743059: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N

2019-11-30 08:24:02.743115: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9755 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)

11-30 08:24:02 Generating testing graph on 1 GPUs ...

11-30 08:24:05 Initialized model weights from /home/pf/mvpose/backend/tf_cpn/log/model_dump/snapshot_350.ckpt ...

11-30 08:24:06 Current epoch is 350.

/home/pf/mvpose/backend/CamStyle/reid/models/resnet.py:49: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.

init.kaiming_normal(self.feat.weight, mode='fan_out')

/home/pf/mvpose/backend/CamStyle/reid/models/resnet.py:50: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.

init.constant(self.feat.bias, 0)

/home/pf/mvpose/backend/CamStyle/reid/models/resnet.py:51: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.

init.constant(self.feat_bn.weight, 1)

/home/pf/mvpose/backend/CamStyle/reid/models/resnet.py:52: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.

init.constant(self.feat_bn.bias, 0)

/home/pf/mvpose/backend/CamStyle/reid/models/resnet.py:60: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.

init.normal(self.classifier.weight, std=0.001)

/home/pf/mvpose/backend/CamStyle/reid/models/resnet.py:61: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.

init.constant(self.classifier.bias, 0)

=> Loaded checkpoint '/home/pf/mvpose/backend/CamStyle/logs/market-ide-camstyle-re/checkpoint.pth.tar'

=> Start epoch 50

48%|██████████████████████████████████████████▎                                             | 38/79 [10:01<10:48, 15.83s/it]/home/pf/mvpose/src/m_utils/visualize.py:379: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.

plt.subplot ( rows, cols, cam_id * cols + i + 2 )

/home/pf/mvpose/src/m_utils/visualize.py:379: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.

plt.subplot ( rows, cols, cam_id * cols + i + 2 )

100%|████████████████████████████████████████████████████████████████████████████████████████| 79/79 [16:02<00:00, 12.19s/it]

Traceback (most recent call last):

File "./src/m_utils/demo.py", line 95, in 

time.localtime ( time.time () ) ) + '.pkl' ), 'wb' ) as f:

FileNotFoundError: [Errno 2] No such file or directory: '/home/pf/mvpose/result/Campus_2019_11_30_08_40.pkl'

it seems there omiss a pkl file ? when the demo start, i have to shutdown the current picture,then would  continue.is it normal?



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/zju3dv/mvpose/issues/35?email_source=notifications\u0026email_token=AFMW3PT4TC72QRXPSLPIMU3QWGZXVA5CNFSM4JTEI362YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4H47ARLA",

"url": "https://github.com/zju3dv/mvpose/issues/35?email_source=notifications\u0026email_token=AFMW3PT4TC72QRXPSLPIMU3QWGZXVA5CNFSM4JTEI362YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4H47ARLA",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by biexiangduo** [comment]
it seems the .pkl file is built the end of "python ./src/m_utils/demo.py -d Campus"
because this file's name has time label.

**Comment by JiangWenPL** [comment]
Yes I know. But our program needs that folder to save aforementioned pickle
file.
