### ISSUE TITLE
ValueError: Does not understand character buffer dtype format string ('?')

### ISSUE THREAD

**Issue by lan786** [zju3dv/mvpose#37]
@DongJT1996 Hi, I'm getting this error when I run demo.py

    Traceback (most recent call last):
    File "./src/m_utils/demo.py", line 94, in <module>
    pose_in_range = export ( test_model, test_loader, is_info_dicts=bool ( args.dumped_dir ), 
    show=True )
    File "./src/m_utils/demo.py", line 46, in export show=show, plt_id=img_id )
    File "/project/mvpose/src/models/estimate3d.py", line 43, in predict return 
    self._estimate3d ( 0, show=show, plt_id=plt_id )
    File "/project/mvpose/src/models/estimate3d.py", line 119, in _estimate3d 
    dual_stochastic_SVT=self.cfg.dual_stochastic_SVT )
    File "/project/mvpose/src/models/matchSVT.py", line 93, in matchSVT 
    match_mat = transform_closure ( X_bin.numpy() )
    File "pictorial.pyx", line 201, in pictorial.transform_closure
    ValueError: Does not understand character buffer dtype format string ('?')

I checked on different sources by Google it and it seems that it's due to Cython. 
My Cython version is 0.29.6 and Numpy version is 1.16.2 with Python 3.6

Moreover I also tried it in Python 3.5 but in Python 3.5 I got this error. 
`File "./src/m_utils/demo.py", line 77
    logger.error ( f"Unknown datasets name: {dataset_name}" )
                                                                                            ^
SyntaxError: invalid syntax`

Kindly help me to solve this problem.

**Comment by lan786** [comment]
I solved this problem this problem was due to pytorch version, I am using torch 1.1.0.  
On line 93 update this code `match_mat = transform_closure ( X_bin.numpy().astype(np.uint8) )`
in `src/models/matchSVT.py` file
