### ISSUE TITLE
RuntimeError: "argmax_cpu" not implemented for 'Bool'

### ISSUE THREAD

**Issue by ssw2002com** [zju3dv/mvpose#43]
Hi, 
   I come across a problem.How can I fix it? thanks:
Traceback (most recent call last):
  File "./src/m_utils/demo.py", line 92, in <module>
    pose_in_range = export ( test_model, test_loader, is_info_dicts=bool ( args.dumped_dir ), show=True )
  File "./src/m_utils/demo.py", line 44, in export
    show=show, plt_id=img_id )
  File "/home/ssw/workspace/mvpose/src/models/estimate3d.py", line 43, in predict
    return self._estimate3d ( 0, show=show, plt_id=plt_id )
  File "/home/ssw/workspace/mvpose/src/models/estimate3d.py", line 128, in _estimate3d
    pid = row.argmax ()
RuntimeError: "argmax_cpu" not implmented for 'Bool'

**Comment by ssw2002com** [comment]
I solved it by install torch==1.2.0 
pip install torch=1.2.0
